ui: mocha-bdd
browsers:
  - name: chrome
    version: 52..latest
  - name: ie
    version: 10..latest
  - name: edge
    version: 13..latest
  - name: firefox
    version: 48..latest
  - name: safari
    version: 8..latest
